name: athlas_play

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
  protoc_plugin: ^20.0.1
  rps: ^0.6.4

scripts:
  generate_pb:
    protoc --proto_path=../proto ../proto/*.proto --dart_out=.
